export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const SET_CONTENT = 'SET_CONTENT'
export const REMOVE_CONTENT = 'REMOVE_CONTENT'
export const SEEK = 'SEEK'
